#####################################
#                                   #
#  @author      : 00xWolf           #
#    GitHub    : @mmsaeed509       #
#    Developer : Mahmoud Mohamed   #
#  﫥  Copyright : Exodia OS         #
#                                   #
#####################################

import = ["/usr/share/exodia/dwm/alacritty/colors.toml", "/usr/share/exodia/dwm/alacritty/fonts.toml"]
live_config_reload = true
# "window.opacity" = 0.95

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 1000
# multiplier = 3
startup_mode = "Windowed"

[window.dimensions]
columns = 114
lines = 40

[window.padding]
x = 10
y = 10
